### ISSUE TITLE
Unable to get the Login windows to authenticate.

### ISSUE THREAD

**Issue by jlucgauthier** [Azure/wordpress-linux-appservice#60] opened 2023-02-12 18:32 UTC
Hi,

When I'm running the tool (v 1.0.0 x86 or x64) with regular access, it closed, With elevated privilege I don't get the authentication pop-up and while selecting the **Subscription** filed in the **Source Site** and clicking on **Select a Subscription**, I get an exception error:

![image](https://user-images.githubusercontent.com/34319312/218329129-cd14e425-3777-4809-bf86-189bb6d153eb.png)

![image](https://user-images.githubusercontent.com/34319312/218329198-902add35-f0d1-4438-877e-8664aa00c206.png)

The error relates to **JiT** but the tenant isn't configured with Just in Time access and doesn't even have the Azure AD Premium 2 licence?

I'v got VS Pro 2022 w/ .Net 6 installed.

![image](https://user-images.githubusercontent.com/34319312/218329524-ccb79004-6171-48cf-850a-8b2d8bfb7f90.png)

Is there a workaround to get the access token so the tool can use it? I didn't try using PS with Az modules to connect has it's not the same context.

_P.N. my workstation is onboarded with MS Defender and Microsoft Endpoint Management (Intune), if there's any related issues._

Thank you for your help!

**The error details:**

```Consultez la fin de ce message pour plus de détails sur l'appel du débogage
juste-à-temps (JIT) à la place de cette boîte de dialogue.

************** Texte de l'exception **************
System.ArgumentNullException: Value cannot be null. (Parameter 'id')
   at Azure.Core.Argument.AssertNotNull[T](T value, String name)
   at Azure.ResourceManager.ArmResource..ctor(ArmClient client, ResourceIdentifier id)
   at Azure.ResourceManager.Resources.SubscriptionResource..ctor(ArmClient client, ResourceIdentifier id)
   at Azure.ResourceManager.Resources.SubscriptionResource..ctor(ArmClient client, SubscriptionData data)
   at Azure.ResourceManager.Resources.SubscriptionCollection.Get(String subscriptionId, CancellationToken cancellationToken)
   at WordPressMigrationTool.Utilities.AzureManagementUtils.GetResourceGroupsInSubscription(String subscriptionId, SubscriptionCollection subscriptions)
   at WordPressMigrationTool.MigrationUX.winSubscriptionChangeWorker_DoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)


************** Assemblys chargés **************
System.Private.CoreLib
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
WordPressMigrationTool
    Version de l'assembly : 1.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Runtime
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 6.0.2.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.ComponentModel.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Windows.Forms.Primitives
    Version de l'assembly : 6.0.2.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Runtime.InteropServices
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Drawing.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Collections.Specialized
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Threading
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Diagnostics.TraceSource
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Collections
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Drawing.Common
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
Microsoft.Win32.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.ComponentModel.EventBasedAsync
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Threading.Thread
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
Accessibility
    Version de l'assembly : 4.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.ComponentModel.TypeConverter
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Numerics.Vectors
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Memory
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.ComponentModel
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
Microsoft.Win32.SystemEvents
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
Azure.Identity
    Version de l'assembly : 1.7.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
Azure.Core
    Version de l'assembly : 1.25.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
netstandard
    Version de l'assembly : 2.1.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Threading.Tasks.Extensions
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.ObjectModel
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Linq
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Collections.NonGeneric
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Net.Http
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Net.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Diagnostics.DiagnosticSource
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Diagnostics.Tracing
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Security.Cryptography.X509Certificates
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Security.Cryptography.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Net.Security
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Private.Uri
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
Microsoft.Identity.Client
    Version de l'assembly : 4.39.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
Azure.ResourceManager
    Version de l'assembly : 1.3.1.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
Microsoft.Bcl.AsyncInterfaces
    Version de l'assembly : 1.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Collections.Concurrent
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Linq.Expressions
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Text.Json
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Net.Sockets
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Threading.Overlapped
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Net.NameResolution
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Threading.ThreadPool
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
Microsoft.Win32.Registry
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Text.Encoding.Extensions
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Security.Principal.Windows
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Security.Claims
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Security.Cryptography.Encoding
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Diagnostics.FileVersionInfo
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Runtime.Loader
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 6.0.2.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Diagnostics.StackTrace
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Reflection.Metadata
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------
System.Collections.Immutable
    Version de l'assembly : 6.0.0.0
    Version Win32 : Non applicable
    CodeBase : 
----------------------------------------

************** Débogage JIT **************
```

**Comment by rabollin** [comment] 2023-02-20 04:11
Hi - Are you running this tool in non-english OS? If so which locale is this?

**Comment by joelfmrodrigues** [comment] 2023-02-22 00:25
@rabollin same issue here, no idea what I am missing.
OS running in English

**Comment by joelfmrodrigues** [comment] 2023-02-22 00:33
@jlucgauthier did you find a solution to this issue?

**Comment by rabollin** [comment] 2023-02-22 19:06
@joelfmrodrigues / @jlucgauthier - Issue seem to be little different. Can you share your Windows WordPress site details, so that we can check some of your subscription details in the back end to understand what is blocking the authentication part.

**Comment by joelfmrodrigues** [comment] 2023-02-22 20:58
@rabollin sorry too late, I ended up migrating manually and deleted the Windows instance this morning once new Linux instance was up and running.
On the other end, I think this may be an issue with my machine as I don't even see a pop up to ask me to authenticate

**Comment by rabollin** [comment] 2023-02-23 12:38
I see, thank you for the update @joelfmrodrigues; glad that you migrated manually, and it worked for you. 

@jlucgauthier - Can you confirm if you are still experiencing the issue? If so can you please share your app name so that we can review the details in backend and help you to resolve the issue.

**Comment by rabollin** [comment] 2023-05-04 18:39
Since there is no update on the issue and we could not reproduce it locally closing the issue.

**Closed by rabollin** 2023-05-04 18:39 UTC
