### ISSUE TITLE
Startup script stopped working

### ISSUE THREAD

**Issue by emmigereb** [Azure/wordpress-linux-appservice#106] opened 2023-09-05 16:18 UTC
https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/running_post_startup_scripts.md - suddenly startup script is not working anymore. When we restart the App service all our custom nginx settings disappear. This is a really big big problem. What could have happened?

**Comment by rabollin** [comment] 2023-09-06 07:43
@emmigereb - looking into the issue on priority.

**Comment by emmigereb** [comment] 2023-09-06 07:48
@rabollin when do you think we can expect a solution? We have clients with multisite and they can´t  log in to their sub site ac the nginx setting is not working. How do we solve this?

**Comment by rabollin** [comment] 2023-09-06 08:06
@emmigereb - We are debugging this issue right now and need some time to understand the root cause.  Can you please share the PHP version being used on those websites.

**Comment by ZubaeyrMSFT** [comment] 2023-09-06 08:45
@emmigereb I have just tested the startup scripts, and it seems to be working fine. Can you please validate the logic in your startup script? Did you happen to change it recently, or maybe it got updated mistakenly? 

Can you please run the script directly from WebSSH/SSH console using the below command?
bash /home/dev/startup.sh

**Comment by emmigereb** [comment] 2023-09-06 09:13
@ZubaeyrMSFT i have this in startup.sh:
```
cp /home/nginx-default.conf /etc/nginx/conf.d/default.conf
/usr/sbin/nginx -s reload
```

But when i run bash /home/dev/startup.sh i get this:
`"ginx: invalid option: "-s reload`

The script is according to this page https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/running_post_startup_scripts.md and we have not changed it lately and before it was working.

**Comment by emmigereb** [comment] 2023-09-06 09:14
> @emmigereb - We are debugging this issue right now and need some time to understand the root cause. Can you please share the PHP version being used on those websites.

Publishing model: Container
Container Image: mcr.microsoft.com/appsvc/wordpress-alpine-php:latest

**Comment by emmigereb** [comment] 2023-09-06 10:12
@ZubaeyrMSFT here is the startup.sh file
[startup.sh.txt](https://github.com/Azure/wordpress-linux-appservice/files/12536207/startup.sh.txt)

**Comment by ZubaeyrMSFT** [comment] 2023-09-06 12:27
@emmigereb 
1. I see that there is a **.txt** extension to this file. It should be simply **startup.sh**, not **startup.sh.txt**.
2. Also, I hope **/home/nginx-default.conf** file exists.

**Comment by emmigereb** [comment] 2023-09-06 12:45
@ZubaeyrMSFT
1. I can´t upload .sh to github file so I added .txt. Of course is just startup.sh
2. Yes /home/nginx-default.conf exists 😊 and as i said before it worked nicely until a couple of days ago.

**Comment by emmigereb** [comment] 2023-09-06 13:19
@ZubaeyrMSFT or @rabollin we really need this to get working for the client today. Is there anything else you can do to help us?

**Comment by rabollin** [comment] 2023-09-06 13:26
Can we get on to a call @emmigereb ; a working session will help to resolve this issue.

**Comment by emmigereb** [comment] 2023-09-06 13:33
@rabollin absolutely. Can you use emmi.gereb@softronic.se to book a teams meeting?

**Comment by rabollin** [comment] 2023-09-06 13:40
Does 9 PM IST works for you?

**Comment by ZubaeyrMSFT** [comment] 2023-09-06 16:16
Closing the issue as it has been resolved.

The issue was due to the special **^M** carriage-return character added at end of each line. This was because the file was edited in DOS/Windows OS, whereas in Linux OS end-of-line is marked by a single newline.

**Closed by ZubaeyrMSFT** 2023-09-06 16:16 UTC
