### ISSUE TITLE
Migration tool fails with mySql servername error

### ISSUE THREAD

**Issue by ryan-adler** [Azure/wordpress-linux-appservice#78] opened 2023-04-27 12:07 UTC
Message received:
Invalid MySQL servername found! serverHostName=

Where is it looking for this value?

**Comment by saisubodhMSFT** [comment] 2023-05-30 07:04
Hi @ryan-adler, This message is thrown when the MySQL servername in database connection string of the selected windows app service is invalid.

You can find this database connection string in configurations blade of the windows app service resource as shown

<img width="624" alt="Screenshot 2023-05-30 122601" src="https://github.com/Azure/wordpress-linux-appservice/assets/90855770/f09f950e-d357-422e-9b6e-0ce739c12a3f">

NOTE: Rename the connection string to 'defaultConnection' since having a connection string with a different name will not be picked up by the migration tool.

If you dont find any connection string in configuration blade, then add one named 'defaultConnection' with the following string with the values replaced appropriately.

Database=<Database_name>;Data Source=<Database_servername>;User Id=<Database_username>;Password=<Database_password>

**Comment by rabollin** [comment] 2023-06-29 13:18
@ryan-adler - Is your issue resolved and can this be closed?

**Comment by ryan-adler** [comment] 2023-06-30 07:11
I am sure that the connection string was correct at the time.  In any case, I don't have time to test this anymore, so I suppose you can close it.

**Comment by rabollin** [comment] 2023-06-30 07:13
As confirmed closing the issue

**Closed by rabollin** 2023-06-30 07:13 UTC
