### ISSUE TITLE
Frontdoor, website breaking when i set home page

### ISSUE THREAD

**Issue by The-Real-Adeel** [Azure/wordpress-linux-appservice#77] opened 2023-04-26 17:00 UTC
Hi, I got the deployment working with front door.

However, when I do the most common practice of changing the home page to a specific page:
![Screenshot_20230426_124940_Outlook~2](https://user-images.githubusercontent.com/92893266/234648413-4ee6a0cd-5e23-4086-afca-fa16dedff815.jpg)

The website breaks, with an error too many redirects:
![Screenshot_20230426_125016_Outlook~3](https://user-images.githubusercontent.com/92893266/234648506-4febfadd-11e8-4c3d-bfcf-ecc6c9f83507.jpg)

- This problem exists even if I deploy through the manual deployment from the portal. 
- This also exists if I deploy on my personal azure tenant as well not just our work tenant. 

Which tells me its a problem with the deployment itself (either the container or missing elements on front door)

What can be done to address this?

**Comment by rabollin** [comment] 2023-05-15 16:52
Working on this issue and will get back at the earliest.

**Comment by The-Real-Adeel** [comment] 2023-05-15 18:22
Thank you. Looking forward to your response

**Comment by The-Real-Adeel** [comment] 2023-06-12 17:34
Hi @rabollin, Are you referring to my communication with your colleague Sai? Sorry I was out of office last week just came back to test the suggestions provided by them.

Unfortunately it is not a fix. It fixed the problem but opened up new ones. ie, can access home page without redirects but not others pages like admin page.

I have messaged him directly in teams, not sure if that is the correct protocol to submit a ticket. Would like another remote session to showcase the challenges I am facing now. 

As for the official deployment has there been changes made? I haven't redeployed just edited the wp-config. I would prefer to have the deployment itself fleshed out with AFD as we plan to deploy many sites in the near future. Altering wp-config each time manually is unsustainable for us.

**Comment by The-Real-Adeel** [comment] 2023-06-13 18:37
Just want to follow up @rabollin , I touched base with Sai today and he was able to show me my mistake and get it working!

It seems to work as intended now. Thank you guys for the support.

However, please keep this issue open until there is an update on the deployment itself to include this fix. I would like to be alerted when that happens.

**Comment by rabollin** [comment] 2023-07-28 10:45
@The-Real-Adeel - Thank you for your patience in verifying this issue multiple times, the issue is fully resolved now and the new deployments from Marketplace will have working solution. Can you please validate once and confirm if we can close the issue.

**Comment by The-Real-Adeel** [comment] 2023-07-28 21:10
Validated. it is indeed working!! Thank team for your work.

**Closed** 2023-07-31 18:11 UTC
